apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
spec:
  selector:
    matchLabels:
      app: go-service
  replicas: 1
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
      - name: go-service
        image: alonaka/app:latest
        ports:
        - containerPort: 8080
